version: '3'
services:
  python:
    image: jupyter/minimal-notebook
    ports:
      - "8001:8888"
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=postgres
    container_name: python_app
    #command:
    #  - start-notebook.sh --NotebookApp.token='ben'
    volumes:
      - "./:/opt/python_app/"
    links:
       - db
  db:
    image: mdillon/postgis
    container_name: postgis
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=postgres
    volumes:
      - "./DB/:/var/lib/postgresql"
    ports:
       - "5555:5432"
